"""cost_fee

Revision ID: 052d5d35fca1
Revises: 42ac59b40a33
Create Date: 2019-09-04 16:43:14.168921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052d5d35fca1'
down_revision = '42ac59b40a33'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_fee_config', sa.Column('cost_type', sa.Integer(), nullable=True, comment='扣费类型'))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_fee_config', 'cost_type')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

