"""uix_bank_card_no_merchant

Revision ID: 0a394de23717
Revises: d95ed2acdeac
Create Date: 2019-09-06 20:17:47.254156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a394de23717'
down_revision = 'd95ed2acdeac'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_bank_card_no_merchant', 'bank_card', ['card_no', 'merchant'])
    op.drop_index('uix_bank_card_no_uid_merchant', table_name='bank_card')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_bank_card_no_uid_merchant', 'bank_card', ['card_no', 'uid', 'merchant'], unique=True)
    op.drop_constraint('uix_bank_card_no_merchant', 'bank_card', type_='unique')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

