"""tst_order_gid

Revision ID: 31060a18429b
Revises: 4e3042b11079
Create Date: 2019-09-05 15:32:53.537367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31060a18429b'
down_revision = '4e3042b11079'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tst_gidX',
    sa.Column('create_time', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='订单ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_tst_gid')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tst_gid',
    sa.Column('create_time', sa.INTEGER(), nullable=False),
    sa.Column('update_time', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('sys_tx_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('mch_tx_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('channel_tx_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('tx_amount', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.SMALLINT(), nullable=False),
    sa.Column('p_method', sa.SMALLINT(), nullable=True),
    sa.Column('state', sa.SMALLINT(), nullable=False),
    sa.Column('settle', sa.SMALLINT(), nullable=False),
    sa.Column('deliver', sa.SMALLINT(), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.Column('mch_fee_id', sa.INTEGER(), nullable=True),
    sa.Column('notify_url', sa.VARCHAR(length=256), nullable=True),
    sa.Column('extra', sa.TEXT(), nullable=True),
    sa.Column('merchant', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mch_tx_id'),
    sa.UniqueConstraint('sys_tx_id')
    )
    op.drop_table('order_tst_gidX')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

