"""user_bind

Revision ID: 474510929175
Revises: 5742a8809047
Create Date: 2019-09-17 16:19:17.248268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474510929175'
down_revision = '5742a8809047'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bind',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('create_time', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('account', sa.String(length=32), nullable=False, comment='账号'),
    sa.Column('bind_type', sa.SmallInteger(), nullable=False, comment='绑定类型'),
    sa.Column('merchant', sa.Integer(), nullable=False, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'bind_type', 'merchant', name='uix_user_bind_name_bind_type_merchant')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bind')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

