"""bank_transfer_log

Revision ID: 54b872a7b08c
Revises: 97c24a6496fd
Create Date: 2019-09-19 11:00:31.533288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b872a7b08c'
down_revision = '97c24a6496fd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_transfer_log',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='订单ID'),
    sa.Column('create_time', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('in_account', sa.Text(), nullable=True, comment='收款银行卡号'),
    sa.Column('out_name', sa.String(length=32), nullable=True, comment='出款人姓名'),
    sa.Column('amount', sa.BigInteger(), nullable=False, comment='订单发起金额'),
    sa.Column('state', sa.SmallInteger(), nullable=False, comment='订单状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_transfer_log_create_time'), 'order_transfer_log', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_transfer_log_create_time'), table_name='order_transfer_log')
    op.drop_table('order_transfer_log')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

