"""user_bind_info

Revision ID: 5e50a12bddfe
Revises: 9d7e9fa7f609
Create Date: 2019-09-18 14:38:54.346572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e50a12bddfe'
down_revision = '9d7e9fa7f609'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bind_info',
    sa.Column('create_time', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
    sa.Column('account', sa.String(length=32), nullable=False, comment='账号'),
    sa.Column('bind_type', sa.SmallInteger(), nullable=False, comment='绑定类型'),
    sa.Column('merchant', sa.Integer(), nullable=False, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'bind_type', 'merchant', name='uix_user_bind_name_bind_type_merchant')
    )
    op.create_index(op.f('ix_user_bind_info_account'), 'user_bind_info', ['account'], unique=False)
    op.drop_index('name', table_name='user_bind')
    op.drop_index('uix_user_bind_name_bind_type_merchant', table_name='user_bind')
    op.drop_table('user_bind')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bind',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='名称'),
    sa.Column('account', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False, comment='账号'),
    sa.Column('bind_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False, comment='绑定类型'),
    sa.Column('merchant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='商户ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uix_user_bind_name_bind_type_merchant', 'user_bind', ['name', 'bind_type', 'merchant'], unique=True)
    op.create_index('name', 'user_bind', ['name'], unique=True)
    op.drop_index(op.f('ix_user_bind_info_account'), table_name='user_bind_info')
    op.drop_table('user_bind_info')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

