"""channel_delete

Revision ID: 97c24a6496fd
Revises: 608bd52ba640
Create Date: 2019-09-19 09:42:39.510267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c24a6496fd'
down_revision = '608bd52ba640'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_config', sa.Column('valid', sa.SmallInteger(), nullable=True, comment='是否删除'))
    op.add_column('proxy_channel_config', sa.Column('valid', sa.SmallInteger(), nullable=True, comment='是否删除'))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy_channel_config', 'valid')
    op.drop_column('channel_config', 'valid')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

