"""channel_router

Revision ID: af05cb1e92ab
Revises: 54b872a7b08c
Create Date: 2019-09-19 16:44:02.236199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af05cb1e92ab'
down_revision = '54b872a7b08c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_router2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('create_time', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('interface', sa.SmallInteger(), nullable=True, comment='接入类型'),
    sa.Column('amount_min', sa.Integer(), nullable=True, comment='交易金额下限'),
    sa.Column('amount_max', sa.Integer(), nullable=True, comment='交易金额上限'),
    sa.Column('merchants', sa.Text(), nullable=True, comment='商户列表'),
    sa.Column('uid_list', sa.Text(), nullable=True, comment='用户列表'),
    sa.Column('channel', sa.Integer(), nullable=False, comment='通道类型'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_router2')
    # ### end Alembic commands ###


def upgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_BACK():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

